apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-read-green
  namespace: snmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-read
      version: green
  template:
    metadata:
      labels:
        app: alert-read
        version: green
    spec:
      containers:
        - name: alert-read-container
          image: 10.161.5.175:5000/alert-read-service:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8089