apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-green
  namespace: snmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
      version: green
  template:
    metadata:
      labels:
        app: kafka-producer
        version: green
    spec:
      containers:
        - name: kafka-container
          image: 10.161.5.175:5000/kafka-producer:10
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "10.161.5.175:9092"