apiVersion: v1
kind: Service
metadata:
  name: snmp-bluegreen-service
  namespace: snmp

spec:
  type: NodePort

  selector:
    app: snmp-microservice
    version: blue

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30095