apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-service
spec:
  type: NodePort
  selector:
    app: snmp-trap-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP

    - name: snmp-trap
      port: 162
      targetPort: 162
      protocol: UDP
